### PR TITLE
Add a simple Json API to query the status of the latest check

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Just a simple one to start with, we can build on that if we need more

cc @shakthimaan

### CODE REVIEW

**Comment by shakthimaan** [comment]
Would it be possible to deploy the same on a test or staging instance?

**Comment by kit-ty-kate** [comment]
It’s already deployed in http://check.ocamllabs.io:8082/api/v1/latest/packages feel free to use it for testing

**Comment by kit-ty-kate** [comment]
If the current simple API suits you, i’ll merge it and deploy it on all the other instances.
After that if you need more specialised endpoints you can open a issues here

**Comment by shakthimaan** [comment]
Thanks! Please merge it and deploy the same on the other instances, and I shall follow-up on more specialized endpoints.

**Comment by kit-ty-kate** [comment]
Merged and deployed.

**Pull request merged**
